### ISSUE TITLE
s8+ wlan can not open

### ISSUE THREAD

**Issue by ucxl** [GrifoDev/IronKernel#1]
flash IronKernel s8+ wlan can not open

**Comment by Tkkg1994** [comment]
Hello
This kernel works only on Galaxy Note 8 roms. You are maybe using a S8/S8+ rom!

**Comment by ucxl** [comment]
Thank you. It works

**Comment by ucxl** [comment]
But fast charging do not work

**Comment by Tkkg1994** [comment]
Logs may help me to solve this issue :)

**Comment by ucxl** [comment]
Great God, there is no way to log, but 1.1.1 has fast charge, 1.1.2 does not fast charge

**Comment by Tkkg1994** [comment]
And V1.1.3?

**Comment by ucxl** [comment]
1.1.3 fast charge works  Thank you very much !
